### PR TITLE
Add BuiltWithDot.Net badge to README

### PR DESCRIPTION
**Pull request by Corstiaan84**
Since The Urlist is listed on BuiltWithDot.Net I've taken the liberty to raise a PR that adds the BuiltWithDot.Net badge for The Urlist to the README.md file. This will help promote your project, BuiltWithDot.Net, all other .NET developers that have projects listed on the site, and the open-source .NET ecosystem in general. If you have any questions or concerns, please let me know. Your help is much appreciated!

Thanks, Corstiaan (creator of BuiltWithDot.Net)

PS If you don't want to add the badge, that's totally fine. Just close this PR. No hard feelings :-)

### CODE REVIEW

**Review by burkeholland — COMMENTED** [review]
Well well well - our first PR! How could we possibly say no? I mean, we could probably think of a reason, but I don't know what it would be. @Jon let's merge this Friday or at least fight about it on stream.

**Comment by jongalloway** [comment]
Love it! We should definitely merge this on stream. Thanks, @Corstiaan84!!!

**Comment by Corstiaan84** [comment]
Thanks @burkeholland and @jongalloway 😄. I'm assuming the stream will be here? https://dotnet.microsoft.com/en-us/live

**Review by burkeholland — COMMENTED** [review]
LGTM!

**Review by burkeholland — COMMENTED** [review]
SHIP IT

**Pull request merged**
